[package]
name = "newmark_rs"
version = "0.0.1"
edition = "2021"
include = ["src/lib.rs", "pyproject.toml"]

[lib]
name = "newmark_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
numpy = "0.20"

[profile.release]
opt-level = 3
